#!/bin/bash

echo "If you like set Radar dns enter number 1
if you like to set 403 dns enter number 2
if you like to set Shecan dns enter number 3
if you like to set Electro dns enter number 4
and other set default dns setting!"

read number

cd /etc/
chmod 777 resolv.conf
cat /dev/null > resolv.conf

if [ $number -eq 1 ]; then
echo "# Generated by NetworkManager
nameserver 10.202.10.10
nameserver 10.202.10.11" > resolv.conf


elif [ $number -eq 2 ]; then
echo "# Generated by NetworkManager
nameserver 10.202.10.202
nameserver 10.202.10.102" > resolv.conf


elif [ $number -eq 3 ]; then
echo "# Generated by NetworkManager
nameserver 178.22.122.100
nameserver 185.51.200.2" > resolv.conf

elif [ $number -eq 4 ]; then
echo "# Generated by NetworkManager
nameserver 78.157.42.100
nameserver 78.157.42.101" > resolv.conf

else
echo "# Generated by NetworkManager
nameserver 192.168.1.1" > resolv.conf
fi

chmod 544 resolv.conf
